version: "3"
services:
  balancefy:
    build: 
      context: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - balancefydb
  balancefydb:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=balancefy
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/mysql
      - ./migration.sql:/docker-entrypoint-initdb.d/migration.sql
volumes:
  db:
